language: python

python:
  - 3.5
  - 3.6
  
services: postgresql


install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER webgis_user WITH PASSWORD 'webgis_password';"
  - psql -c "CREATE DATABASE webgis_db;" -U webgis_user


script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test