language: python

python:
  - "3.6"

install:
  - "pip3 install -r requirements.txt"

script:
  - "python manage.py makemigrations --settings=main.settings.dev"
  - "python manage.py migrate --settings=main.settings.dev"
  # this needs to be fixed to run more than just unit tests
  - "python manage.py test test.unit_tests --settings=main.settings.dev"