language:
  - python

python:
  - "3.5"
  - "3.6"

install:
  - "pip3 install -r requirements_test.txt"

script:
  - "python manage.py makemigrations"
  - "python manage.py migrate"
  - "python manage.py test"
