language:
  - python

python:
  - "3.6"

install:
  - "pip3 install -r requirements.txt"

#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - "python manage.py makemigrations --settings=main.settings.dev"
  - "python manage.py migrate --settings=main.settings.dev"
  - "python manage.py test test.unit_tests --settings=main.settings.dev"
