version: "3"

services:
  web:
    depends_on:
      - db
    build: .
    #command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn main.wsgi -b 0.0.0.0:8000"
    command: bash -c "./wait-for-it.sh && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn main.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
  db:
    image: postgres